name: Hello World CI/CD

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Hello World
        run: |
          cat hello_world.txt

      - name: Upload artifact
        if: contains(github.event.head_commit.message, 'upload_artifact')
        run: |
          cat hello_world.txt
